import { PrismaClient } from "@prisma/client"

const db = new PrismaClient()

export default async function() {
    console.log('Creating stateCounty records');
    await db.stateCounty.createMany({
        data: [
            { stateCountyId: 1, state: 'OH', county: 'Adams' },
            { stateCountyId: 2, state: 'OH', county: 'Allen' },
            { stateCountyId: 3, state: 'OH', county: 'Ashland' },
            { stateCountyId: 4, state: 'OH', county: 'Ashtabula' },
            { stateCountyId: 5, state: 'OH', county: 'Athens' },
            { stateCountyId: 6, state: 'OH', county: 'Auglaize' },
            { stateCountyId: 7, state: 'OH', county: 'Belmont' },
            { stateCountyId: 8, state: 'OH', county: 'Brown' },
            { stateCountyId: 9, state: 'OH', county: 'Butler' },
            { stateCountyId: 10, state: 'OH', county: 'Carroll' },
            { stateCountyId: 11, state: 'OH', county: 'Champaign' },
            { stateCountyId: 12, state: 'OH', county: 'Clark' },
            { stateCountyId: 13, state: 'OH', county: 'Clermont' },
            { stateCountyId: 14, state: 'OH', county: 'Clinton' },
            { stateCountyId: 15, state: 'OH', county: 'Columbiana' },
            { stateCountyId: 16, state: 'OH', county: 'Coshocton' },
            { stateCountyId: 17, state: 'OH', county: 'Crawford' },
            { stateCountyId: 18, state: 'OH', county: 'Cuyahoga' },
            { stateCountyId: 19, state: 'OH', county: 'Darke' },
            { stateCountyId: 20, state: 'OH', county: 'Defiance' },
            { stateCountyId: 21, state: 'OH', county: 'Delaware' },
            { stateCountyId: 22, state: 'OH', county: 'Erie' },
            { stateCountyId: 23, state: 'OH', county: 'Fairfield' },
            { stateCountyId: 24, state: 'OH', county: 'Fayette' },
            { stateCountyId: 25, state: 'OH', county: 'Franklin' },
            { stateCountyId: 26, state: 'OH', county: 'Fulton' },
            { stateCountyId: 27, state: 'OH', county: 'Gallia' },
            { stateCountyId: 28, state: 'OH', county: 'Geauga' },
            { stateCountyId: 29, state: 'OH', county: 'Greene' },
            { stateCountyId: 30, state: 'OH', county: 'Guernsey' },
            { stateCountyId: 31, state: 'OH', county: 'Hamilton' },
            { stateCountyId: 32, state: 'OH', county: 'Hancock' },
            { stateCountyId: 33, state: 'OH', county: 'Hardin' },
            { stateCountyId: 34, state: 'OH', county: 'Harrison' },
            { stateCountyId: 35, state: 'OH', county: 'Henry' },
            { stateCountyId: 36, state: 'OH', county: 'Highland' },
            { stateCountyId: 37, state: 'OH', county: 'Hocking' },
            { stateCountyId: 38, state: 'OH', county: 'Holmes' },
            { stateCountyId: 39, state: 'OH', county: 'Huron' },
            { stateCountyId: 40, state: 'OH', county: 'Jackson' },
            { stateCountyId: 41, state: 'OH', county: 'Jefferson' },
            { stateCountyId: 42, state: 'OH', county: 'Knox' },
            { stateCountyId: 43, state: 'OH', county: 'Lake' },
            { stateCountyId: 44, state: 'OH', county: 'Lawrence' },
            { stateCountyId: 45, state: 'OH', county: 'Licking' },
            { stateCountyId: 46, state: 'OH', county: 'Logan' },
            { stateCountyId: 47, state: 'OH', county: 'Lorain' },
            { stateCountyId: 48, state: 'OH', county: 'Lucas' },
            { stateCountyId: 49, state: 'OH', county: 'Madison' },
            { stateCountyId: 50, state: 'OH', county: 'Mahoning' },
            { stateCountyId: 51, state: 'OH', county: 'Marion' },
            { stateCountyId: 52, state: 'OH', county: 'Medina' },
            { stateCountyId: 53, state: 'OH', county: 'Meigs' },
            { stateCountyId: 54, state: 'OH', county: 'Mercer' },
            { stateCountyId: 55, state: 'OH', county: 'Miami' },
            { stateCountyId: 56, state: 'OH', county: 'Monroe' },
            { stateCountyId: 57, state: 'OH', county: 'Montgomery' },
            { stateCountyId: 58, state: 'OH', county: 'Morgan' },
            { stateCountyId: 59, state: 'OH', county: 'Morrow' },
            { stateCountyId: 60, state: 'OH', county: 'Muskingum' },
            { stateCountyId: 61, state: 'OH', county: 'Noble' },
            { stateCountyId: 62, state: 'OH', county: 'Ottawa' },
            { stateCountyId: 63, state: 'OH', county: 'Paulding' },
            { stateCountyId: 64, state: 'OH', county: 'Perry' },
            { stateCountyId: 65, state: 'OH', county: 'Pickaway' },
            { stateCountyId: 66, state: 'OH', county: 'Pike' },
            { stateCountyId: 67, state: 'OH', county: 'Portage' },
            { stateCountyId: 68, state: 'OH', county: 'Preble' },
            { stateCountyId: 69, state: 'OH', county: 'Putnam' },
            { stateCountyId: 70, state: 'OH', county: 'Richland' },
            { stateCountyId: 71, state: 'OH', county: 'Ross' },
            { stateCountyId: 72, state: 'OH', county: 'Sandusky' },
            { stateCountyId: 73, state: 'OH', county: 'Scioto' },
            { stateCountyId: 74, state: 'OH', county: 'Seneca' },
            { stateCountyId: 75, state: 'OH', county: 'Shelby' },
            { stateCountyId: 76, state: 'OH', county: 'Stark' },
            { stateCountyId: 77, state: 'OH', county: 'Summit' },
            { stateCountyId: 78, state: 'OH', county: 'Trumbull' },
            { stateCountyId: 79, state: 'OH', county: 'Tuscarawas' },
            { stateCountyId: 80, state: 'OH', county: 'Union' },
            { stateCountyId: 81, state: 'OH', county: 'Van Wert' },
            { stateCountyId: 82, state: 'OH', county: 'Vinton' },
            { stateCountyId: 83, state: 'OH', county: 'Warren' },
            { stateCountyId: 84, state: 'OH', county: 'Washington' },
            { stateCountyId: 85, state: 'OH', county: 'Wayne' },
            { stateCountyId: 86, state: 'OH', county: 'Williams' },
            { stateCountyId: 87, state: 'OH', county: 'Wood' },
            { stateCountyId: 88, state: 'OH', county: 'Wyandot' },
            { stateCountyId: 89, state: 'OH', county: 'UNKNOWN' },
        ]
    });
}