import { PrismaClient } from "@prisma/client";
const db = new PrismaClient();

export default async function () {
  console.log("Creating site records");
  const [counties, states] = await Promise.all([
    db.county.findMany(),
    db.state.findMany(),
  ]);
  const countyLookup = Object.assign(
    {},
    ...counties.map((c: any) => ({ [c.name]: c.id })),
  );
  const stateLookup = Object.assign(
    {},
    ...states.map((s: any) => ({ [s.name]: s.id })),
  );
  await db.site.createMany({
    data: [
      {
        id: BigInt(1),
        siteName: "Caley Wildlife Area",
        countyId: countyLookup.Lorain,
        stateId: stateLookup.Ohio,
        township: "Pittsfield",
        locationZip: null,
        siteAddress: null,
        siteAddress2: null,
        siteCity: null,
        siteState: null,
        siteZip: null,
        person: "Jim Ciha",
        personAddress: "3481 West 52nd Street",
        personAddress2: null,
        personCity: "Cleveland",
        personState: "OH",
        personZip: "44102-5802",
        personPhone: "216-631-3952",
        personEmail: null,
        latitudeStart: null,
        longitudeStart: null,
        latitudeEnd: null,
        longitudeEnd: null,
        altPerson: null,
        altPersonAddress: null,
        altPersonAddress2: null,
        altPersonCity: null,
        altPersonState: null,
        altPersonZip: null,
        altPersonPhone: null,
        altPersonEmail: null,
        otherParticipants: null,
        description:
          "Old pond surrounded by pine trees. Old tractor paths through woods. Foot path leads to a wooden bridge over Wellington Creek.Through older growth woods. Younger forest on upper part of paths, then old fields along edge of woods. Open fields along a n",
        s1995: 4,
        s1996: 3,
        s1997: 3,
        s1998: 3,
        s1999: 3,
        s2000: 1,
        s2001: 5,
        s2002: 5,
        s2003: 5,
        s2004: 5,
        createdAt: new Date("9/6/1999 4:16:54 PM GMT-5").toISOString(),
      },
      {
        id: BigInt(2),
        siteName: "Terra Vista",
        countyId: countyLookup.Cuyahoga,
        stateId: stateLookup.Ohio,
        township: "Valley View Village",
        locationZip: "44125",
        siteAddress: null,
        siteAddress2: null,
        siteCity: null,
        siteState: null,
        siteZip: null,
        person: "Meg Benke Plona",
        personAddress: "Cuyahoga Valley Nat'l Rec. Area",
        personAddress2: "15610 Vaughn Road",
        personCity: "Brecksville",
        personState: "IO",
        personZip: "44141",
        personPhone: "330 342-0764",
        personEmail: "meg_benke@nps.gov",
        latitudeStart: null,
        longitudeStart: null,
        latitudeEnd: null,
        longitudeEnd: null,
        altPerson: null,
        altPersonAddress: null,
        altPersonAddress2: null,
        altPersonCity: null,
        altPersonState: null,
        altPersonZip: null,
        altPersonPhone: "330 467-9140",
        altPersonEmail: null,
        otherParticipants:
          "Dorothy Hagerling, Martha McCombs, Margaret Seibert, Judy Biscan",
        description: "Fax-440 546-5943",
        s1995: 4,
        s1996: 3,
        s1997: 3,
        s1998: 3,
        s1999: 3,
        s2000: 5,
        s2001: 5,
        s2002: 5,
        s2003: 5,
        s2004: 5,
        createdAt: new Date("3/28/2000 1:34:09 PM GMT-5").toISOString(),
      },
      {
        id: BigInt(3),
        siteName: "Armington Pond",
        countyId: countyLookup.Summit,
        stateId: stateLookup.Ohio,
        township: null,
        locationZip: null,
        siteAddress: null,
        siteAddress2: null,
        siteCity: null,
        siteState: null,
        siteZip: null,
        person: "Pat Rydquist",
        personAddress: "2274 Victoria Parkway",
        personAddress2: null,
        personCity: "Hudson",
        personState: "OH",
        personZip: "44236",
        personPhone: "330 656-2028",
        personEmail: "rydquist@oh.verio.com",
        latitudeStart: null,
        longitudeStart: null,
        latitudeEnd: null,
        longitudeEnd: null,
        altPerson: "Meg Benke",
        altPersonAddress: "15610 Vaugh Road",
        altPersonAddress2: null,
        altPersonCity: "Brecksville",
        altPersonState: "IO",
        altPersonZip: "44141",
        altPersonPhone: null,
        altPersonEmail: null,
        otherParticipants: null,
        description: null,
        s1995: 4,
        s1996: 3,
        s1997: 3,
        s1998: 4,
        s1999: 4,
        s2000: 5,
        s2001: 5,
        s2002: 5,
        s2003: 5,
        s2004: 5,
        createdAt: new Date("3/16/2000 10:47:14 AM GMT-5").toISOString(),
      },
      {
        id: BigInt(4),
        siteName: "NCR-Meadow/Marsh",
        countyId: countyLookup.Cuyahoga,
        stateId: stateLookup.Ohio,
        township: null,
        locationZip: null,
        siteAddress: null,
        siteAddress2: null,
        siteCity: null,
        siteState: null,
        siteZip: null,
        person: "Deb Marcinski",
        personAddress: "3037 SOM Center Road",
        personAddress2: null,
        personCity: "Willoughby Hills",
        personState: "OH",
        personZip: "44094",
        personPhone: "440 473-3370",
        personEmail: null,
        latitudeStart: "N41 34.216,W81 24.835",
        longitudeStart: "W81 24.835",
        latitudeEnd: null,
        longitudeEnd: null,
        altPerson: null,
        altPersonAddress: null,
        altPersonAddress2: null,
        altPersonCity: null,
        altPersonState: null,
        altPersonZip: null,
        altPersonPhone: null,
        altPersonEmail: null,
        otherParticipants: null,
        description: "Not in 1998 or 1999",
        s1995: 4,
        s1996: 3,
        s1997: 3,
        s1998: 4,
        s1999: 4,
        s2000: 5,
        s2001: 5,
        s2002: 5,
        s2003: 5,
        s2004: 5,
        createdAt: new Date("11/5/1999 11:33:13 AM GMT-5").toISOString(),
      },
      {
        id: BigInt(5),
        siteName: "Koelliker Fen",
        countyId: countyLookup.Geauga,
        stateId: stateLookup.Ohio,
        township: "Munson",
        locationZip: null,
        siteAddress: null,
        siteAddress2: null,
        siteCity: null,
        siteState: null,
        siteZip: null,
        person: "Mark Rzeszotarski",
        personAddress: "12811 Vincent Drive",
        personAddress2: null,
        personCity: "Chesterland",
        personState: "OH",
        personZip: "44026",
        personPhone: "440 729-8102",
        personEmail: null,
        latitudeStart: "N41 33",
        longitudeStart: "W 81 17",
        latitudeEnd: null,
        longitudeEnd: null,
        altPerson: null,
        altPersonAddress: null,
        altPersonAddress2: null,
        altPersonCity: null,
        altPersonState: null,
        altPersonZip: null,
        altPersonPhone: null,
        altPersonEmail: null,
        otherParticipants: null,
        description: "Off Wilson Mills Road",
        s1995: 3,
        s1996: 3,
        s1997: 3,
        s1998: 1,
        s1999: 4,
        s2000: 5,
        s2001: 5,
        s2002: 5,
        s2003: 5,
        s2004: 5,
        createdAt: new Date("10/5/1999 10:08:10 AM GMT-5").toISOString(),
      },
      {
        id: BigInt(6),
        siteName: "Luce Creek",
        countyId: countyLookup.Cuyahoga,
        stateId: stateLookup.Ohio,
        township: null,
        locationZip: null,
        siteAddress: null,
        siteAddress2: null,
        siteCity: null,
        siteState: null,
        siteZip: null,
        person: "Stephanie Gall",
        personAddress: "1240 Cross Creek Dr. #48",
        personAddress2: null,
        personCity: "Brunswick",
        personState: "OH",
        personZip: "44212-3067",
        personPhone: "330 273-1336",
        personEmail: "steph@popbit.com",
        latitudeStart: null,
        longitudeStart: null,
        latitudeEnd: null,
        longitudeEnd: null,
        altPerson: "Katherine Lublin",
        altPersonAddress: "3439 Superior Park Dr. #306",
        altPersonAddress2: null,
        altPersonCity: "Cleveland Heights",
        altPersonState: "OH",
        altPersonZip: "44118",
        altPersonPhone: "216 321-8604",
        altPersonEmail: "klublin@cmnh.org",
        otherParticipants: null,
        description: null,
        s1995: 4,
        s1996: 3,
        s1997: 3,
        s1998: 3,
        s1999: 3,
        s2000: 2,
        s2001: 5,
        s2002: 5,
        s2003: 5,
        s2004: 5,
        createdAt: new Date("3/28/2000 11:13:08 AM GMT-5").toISOString(),
      },
      {
        id: BigInt(7),
        siteName: "Penitentiary Glen",
        countyId: countyLookup.Lake,
        stateId: stateLookup.Ohio,
        township: null,
        locationZip: "44099",
        siteAddress: null,
        siteAddress2: null,
        siteCity: null,
        siteState: null,
        siteZip: null,
        person: "Jerome L. Wiedmann",
        personAddress: "12764 Huntoon Road",
        personAddress2: null,
        personCity: "Painesville",
        personState: "OH",
        personZip: "44077",
        personPhone: "440 254-4230",
        personEmail: "Wiedmann_J@Ricerca.com",
        latitudeStart: "N 41 36 40",
        longitudeStart: "W 81 19 52",
        latitudeEnd: "N41 36 45",
        longitudeEnd: "W81 19 58",
        altPerson: "Jennifer McAnlis",
        altPersonAddress: "8668 Kirtland-Chardon Road",
        altPersonAddress2: null,
        altPersonCity: "Kirtland",
        altPersonState: "IO",
        altPersonZip: "44094",
        altPersonPhone: "440 256-3827",
        altPersonEmail: "pg@Lakemetroparks.com",
        otherParticipants:
          "Julie Clemens, Julie Loomis, Ed Binic,  Andy Wiedmann, Barb Wiedmann",
        description:
          "In Penitentiary Glen Metro Park. Mowed lawns, flower gardens to meadow, brushy meadow, light to dense woods. Sections marked by yellow capped rebar sunk in ground.",
        s1995: 4,
        s1996: 3,
        s1997: 3,
        s1998: 3,
        s1999: 3,
        s2000: 5,
        s2001: 5,
        s2002: 5,
        s2003: 5,
        s2004: 5,
        createdAt: new Date("7/31/2000 1:58:54 PM GMT-5").toISOString(),
      },
      {
        id: BigInt(8),
        siteName: "Huntoon Road",
        countyId: countyLookup.Lake,
        stateId: stateLookup.Ohio,
        township: "Leroy",
        locationZip: "44077",
        siteAddress: null,
        siteAddress2: null,
        siteCity: null,
        siteState: null,
        siteZip: null,
        person: "Jerome L. Wiedmann",
        personAddress: "12764 Huntoon Road",
        personAddress2: null,
        personCity: "Painesville",
        personState: "OH",
        personZip: "44077",
        personPhone: "440 254-4230",
        personEmail: "Wiedmann_J@Ricerca.com",
        latitudeStart: "N 41 41 18",
        longitudeStart: "W 81 10 50",
        latitudeEnd: "N41 41 18,W 81 10 50",
        longitudeEnd: "W 81 10 50",
        altPerson: "Jennifer McAnlis",
        altPersonAddress: "8668 Kirtland-Chardon Road",
        altPersonAddress2: null,
        altPersonCity: "Kirtland",
        altPersonState: "IO",
        altPersonZip: "44094",
        altPersonPhone: "440 256-2106",
        altPersonEmail: "pg@Lakemetroparks.com",
        otherParticipants: "Julie Clemens",
        description:
          "Sec. 2 & 12 are farmground. Sec 2 has corner of Metropark woods. Sections 1, 3-5, 14 & 15 are large lot residential. Sections 6-11 & 13 are meadowland and mewdow/woods border. Sec 1 starts at garage if 12764 Huntoon Road.",
        s1995: 4,
        s1996: 3,
        s1997: 3,
        s1998: 3,
        s1999: 3,
        s2000: 5,
        s2001: 5,
        s2002: 5,
        s2003: 5,
        s2004: 5,
        createdAt: new Date("10/7/1999 11:00:46 AM GMT-5").toISOString(),
      },
      {
        id: BigInt(9),
        siteName: "Resthaven Wildlife Area",
        countyId: countyLookup.Erie,
        stateId: stateLookup.Ohio,
        township: "Margaretta",
        locationZip: null,
        siteAddress: null,
        siteAddress2: null,
        siteCity: null,
        siteState: null,
        siteZip: null,
        person: "Lois Ter Veen",
        personAddress: "3910 E. Perkins Road",
        personAddress2: null,
        personCity: "Huron",
        personState: "OH",
        personZip: "44939",
        personPhone: "419 625-7783",
        personEmail: null,
        latitudeStart: null,
        longitudeStart: null,
        latitudeEnd: null,
        longitudeEnd: null,
        altPerson: null,
        altPersonAddress: null,
        altPersonAddress2: null,
        altPersonCity: null,
        altPersonState: null,
        altPersonZip: null,
        altPersonPhone: null,
        altPersonEmail: null,
        otherParticipants: null,
        description: null,
        s1995: 4,
        s1996: 4,
        s1997: 3,
        s1998: 3,
        s1999: 4,
        s2000: 5,
        s2001: 5,
        s2002: 5,
        s2003: 5,
        s2004: 5,
        createdAt: new Date("5/28/1999 11:08:34 PM GMT-5").toISOString(),
      },
      {
        id: BigInt(10),
        siteName: "Kelleys Island - Bookerman Roa",
        countyId: countyLookup.Erie,
        stateId: stateLookup.Ohio,
        township: "Kelleys Island",
        locationZip: "43438",
        siteAddress: null,
        siteAddress2: null,
        siteCity: null,
        siteState: null,
        siteZip: null,
        person: "Barbara K. Coleman",
        personAddress: "14916 Arden Avenue",
        personAddress2: null,
        personCity: "Lakewood",
        personState: "OH",
        personZip: "44107",
        personPhone: "216 226-0391",
        personEmail: "CMNHdocent@aol.com",
        latitudeStart: "N 41 35",
        longitudeStart: "W 82 42",
        latitudeEnd: null,
        longitudeEnd: null,
        altPerson: "William G. Coleman",
        altPersonAddress: "14916 Arden Avenue",
        altPersonAddress2: null,
        altPersonCity: "Lakewood",
        altPersonState: "IO",
        altPersonZip: "44107",
        altPersonPhone: "216 226-0391",
        altPersonEmail: null,
        otherParticipants: "William G. Coleman",
        description:
          "Open fields, electric right-of-way, shrubby field, area with milkweed patch, mowed lawn and garden area with butterfly feeders.",
        s1995: 4,
        s1996: 4,
        s1997: 3,
        s1998: 3,
        s1999: 3,
        s2000: 1,
        s2001: 5,
        s2002: 5,
        s2003: 5,
        s2004: 5,
        createdAt: new Date("6/26/2000 10:26:50 AM GMT-5").toISOString(),
      },
      {
        id: BigInt(11),
        siteName: "Girdled Road Park",
        countyId: countyLookup.Lake,
        stateId: stateLookup.Ohio,
        township: "Leroy",
        locationZip: "44077",
        siteAddress: null,
        siteAddress2: null,
        siteCity: null,
        siteState: null,
        siteZip: null,
        person: "Jerome L. Wiedmann",
        personAddress: "12764 Huntoon Road",
        personAddress2: null,
        personCity: "Painesville",
        personState: "OH",
        personZip: "44077",
        personPhone: "440 254-4230",
        personEmail: "Wiedmann_J@Ricerca.com",
        latitudeStart: "N 41 38 33",
        longitudeStart: "W 81 10 30",
        latitudeEnd: "N41 38 33",
        longitudeEnd: "W81 10 30",
        altPerson: "Jennifer McAnlis",
        altPersonAddress: "8668 Kirtland, Ohio  44094",
        altPersonAddress2: "Penitentiary Glen Reservation",
        altPersonCity: "Kirtland",
        altPersonState: "IO",
        altPersonZip: "44094",
        altPersonPhone: "440 256-2106",
        altPersonEmail: "pg@Lakemetroparks.com",
        otherParticipants: "Julie Clemens, Julie Loomis",
        description:
          "Transect is mostly meadow. Section 3 is edge of farm. Section 13 is woods. Section 4-10 is mostly treeline. GPS was done prior to new wetlands; sections 10 & 11 were modified.",
        s1995: 4,
        s1996: 4,
        s1997: 3,
        s1998: 3,
        s1999: 3,
        s2000: 5,
        s2001: 5,
        s2002: 5,
        s2003: 5,
        s2004: 5,
        createdAt: new Date("3/27/2000 1:29:48 PM GMT-5").toISOString(),
      },
      {
        id: BigInt(12),
        siteName: "Naturealm",
        countyId: countyLookup.Summit,
        stateId: stateLookup.Ohio,
        township: null,
        locationZip: "44313",
        siteAddress: null,
        siteAddress2: null,
        siteCity: null,
        siteState: null,
        siteZip: null,
        person: "Pat Rydquist",
        personAddress: "1828 Smith Road",
        personAddress2: "2274 Victoria Pky, Hudson, Ohio 44236",
        personCity: "Akron",
        personState: "OH",
        personZip: "44313",
        personPhone: "330 865-8065",
        personEmail: "rydquist@oh.verio.com",
        latitudeStart: "N41 8 21",
        longitudeStart: "W81 39 20",
        latitudeEnd: null,
        longitudeEnd: null,
        altPerson: "Helen Bresley",
        altPersonAddress: "1868 Lillian Road",
        altPersonAddress2: null,
        altPersonCity: "Stow",
        altPersonState: "IO",
        altPersonZip: "44224",
        altPersonPhone: "330 940-3878",
        altPersonEmail: null,
        otherParticipants:
          "Esther Stover, Charles White, Phyllis Dexlin,  Judy Fightmaster",
        description:
          "Sections start at Rose and Herb Garden, through prairie, along wood margins, through service area, behind a pond, through forest and meadow, into the arboretum, and along planted gardens.",
        s1995: 4,
        s1996: 4,
        s1997: 4,
        s1998: 3,
        s1999: 3,
        s2000: 5,
        s2001: 5,
        s2002: 5,
        s2003: 5,
        s2004: 5,
        createdAt: new Date("6/26/2000 1:52:01 PM GMT-5").toISOString(),
      },
      {
        id: BigInt(13),
        siteName: "Kiracofe Prairie",
        countyId: countyLookup.Allen,
        stateId: stateLookup.Ohio,
        township: null,
        locationZip: null,
        siteAddress: null,
        siteAddress2: null,
        siteCity: null,
        siteState: null,
        siteZip: null,
        person: "Rita K. Thelan",
        personAddress: "2355 Ada Road",
        personAddress2: null,
        personCity: "Lima",
        personState: "OH",
        personZip: "45801",
        personPhone: "419 221-1232",
        personEmail: "jampd@wcoil.com",
        latitudeStart: null,
        longitudeStart: null,
        latitudeEnd: null,
        longitudeEnd: null,
        altPerson: null,
        altPersonAddress: null,
        altPersonAddress2: null,
        altPersonCity: null,
        altPersonState: null,
        altPersonZip: null,
        altPersonPhone: null,
        altPersonEmail: null,
        otherParticipants: "Pam Mowbry, F Pauff, B. Obermeyer",
        description:
          "Parts of sections 1 & 2 are parallel to sections 3, 5, & 6. One-half of section 6 will be burnt every other year.",
        s1995: 4,
        s1996: 4,
        s1997: 4,
        s1998: 3,
        s1999: 3,
        s2000: 5,
        s2001: 5,
        s2002: 5,
        s2003: 5,
        s2004: 5,
        createdAt: new Date("3/27/2000 2:35:17 PM GMT-5").toISOString(),
      },
      {
        id: BigInt(14),
        siteName: "Jackson Field",
        countyId: countyLookup.Cuyahoga,
        stateId: stateLookup.Ohio,
        township: null,
        locationZip: null,
        siteAddress: null,
        siteAddress2: null,
        siteCity: null,
        siteState: null,
        siteZip: null,
        person: "Kevin Metcalf",
        personAddress: "3037 SOM Center Road",
        personAddress2: null,
        personCity: "Willoughby Hills",
        personState: "OH",
        personZip: "44094",
        personPhone: "440 473-0648",
        personEmail: null,
        latitudeStart: null,
        longitudeStart: null,
        latitudeEnd: null,
        longitudeEnd: null,
        altPerson: "Heidi Wintersteen",
        altPersonAddress: null,
        altPersonAddress2: null,
        altPersonCity: null,
        altPersonState: null,
        altPersonZip: null,
        altPersonPhone: null,
        altPersonEmail: null,
        otherParticipants: null,
        description: "1999",
        s1995: 4,
        s1996: 3,
        s1997: 3,
        s1998: 3,
        s1999: 3,
        s2000: 5,
        s2001: 5,
        s2002: 5,
        s2003: 5,
        s2004: 5,
        createdAt: new Date("12/2/1999 2:28:34 PM GMT-5").toISOString(),
      },
      {
        id: BigInt(15),
        siteName: "Mentor Marsh",
        countyId: countyLookup.Lake,
        stateId: stateLookup.Ohio,
        township: null,
        locationZip: null,
        siteAddress: null,
        siteAddress2: null,
        siteCity: null,
        siteState: null,
        siteZip: null,
        person: "Yarina Hynd",
        personAddress: null,
        personAddress2: null,
        personCity: null,
        personState: null,
        personZip: null,
        personPhone: null,
        personEmail: null,
        latitudeStart: null,
        longitudeStart: null,
        latitudeEnd: null,
        longitudeEnd: null,
        altPerson: null,
        altPersonAddress: null,
        altPersonAddress2: null,
        altPersonCity: null,
        altPersonState: null,
        altPersonZip: null,
        altPersonPhone: null,
        altPersonEmail: null,
        otherParticipants: null,
        description:
          "Kerven Trail - woods, Kerven Meadow - path, Kerven Trail to lookout - woods, Kerven Meadow - through meadow, pond behind Nature Center - grassy, access road @ Rt. 44.",
        s1995: 4,
        s1996: 4,
        s1997: 4,
        s1998: 3,
        s1999: 4,
        s2000: 5,
        s2001: 5,
        s2002: 5,
        s2003: 5,
        s2004: 5,
        createdAt: new Date("3/28/2000 11:32:38 AM GMT-5").toISOString(),
      },
      {
        id: BigInt(16),
        siteName: "Lakeshore Reservation",
        countyId: countyLookup.Lake,
        stateId: stateLookup.Ohio,
        township: "Perry",
        locationZip: null,
        siteAddress: null,
        siteAddress2: null,
        siteCity: null,
        siteState: null,
        siteZip: null,
        person: "Jennifer McAnlis",
        personAddress: "8668 Kirtland-Chardon Road",
        personAddress2: null,
        personCity: "Kirtland",
        personState: "OH",
        personZip: "44094",
        personPhone: "440 256-2106",
        personEmail: "pg@lakemetroparks.com",
        latitudeStart: "N 41 48 50",
        longitudeStart: "W 81 07 10",
        latitudeEnd: "N41 48 50",
        longitudeEnd: "W81 07 10,",
        altPerson: "John Pogacnik",
        altPersonAddress: null,
        altPersonAddress2: null,
        altPersonCity: null,
        altPersonState: null,
        altPersonZip: null,
        altPersonPhone: null,
        altPersonEmail: null,
        otherParticipants: "John Pogacnik - jlpognacik@lakemetroparks.com",
        description: null,
        s1995: 4,
        s1996: 4,
        s1997: 4,
        s1998: 3,
        s1999: 3,
        s2000: 4,
        s2001: 5,
        s2002: 5,
        s2003: 5,
        s2004: 5,
        createdAt: new Date("3/20/2000 2:15:43 PM GMT-5").toISOString(),
      },
      {
        id: BigInt(17),
        siteName: "Battelle-Darby Creek",
        countyId: countyLookup.Franklin,
        stateId: stateLookup.Ohio,
        township: "Pleasant",
        locationZip: null,
        siteAddress: null,
        siteAddress2: null,
        siteCity: null,
        siteState: null,
        siteZip: null,
        person: "John Watts",
        personAddress: "1069 West Main Streetain Street",
        personAddress2: null,
        personCity: "Westerville",
        personState: "OH",
        personZip: "43081",
        personPhone: "614 891-0700",
        personEmail: null,
        latitudeStart: null,
        longitudeStart: null,
        latitudeEnd: null,
        longitudeEnd: null,
        altPerson: null,
        altPersonAddress: null,
        altPersonAddress2: null,
        altPersonCity: null,
        altPersonState: null,
        altPersonZip: null,
        altPersonPhone: null,
        altPersonEmail: null,
        otherParticipants: "Barb Bloetcher, Christine Hura",
        description: null,
        s1995: 4,
        s1996: 4,
        s1997: 4,
        s1998: 3,
        s1999: 3,
        s2000: 5,
        s2001: 5,
        s2002: 5,
        s2003: 5,
        s2004: 5,
        createdAt: new Date("4/10/2000 1:22:52 PM GMT-5").toISOString(),
      },
      {
        id: BigInt(18),
        siteName: "Wilderness Center",
        countyId: countyLookup.Stark,
        stateId: stateLookup.Ohio,
        township: null,
        locationZip: null,
        siteAddress: null,
        siteAddress2: null,
        siteCity: null,
        siteState: null,
        siteZip: null,
        person: "Robert W. Hawes",
        personAddress: "9877 Alabama Avenue, SW",
        personAddress2: null,
        personCity: "Wilmot",
        personState: "OH",
        personZip: "44689-0202",
        personPhone: "330 359-5235",
        personEmail: null,
        latitudeStart: "N 40 40 26",
        longitudeStart: "W 81 31 22",
        latitudeEnd: null,
        longitudeEnd: null,
        altPerson: null,
        altPersonAddress: null,
        altPersonAddress2: null,
        altPersonCity: null,
        altPersonState: null,
        altPersonZip: null,
        altPersonPhone: null,
        altPersonEmail: null,
        otherParticipants: "Cory Sica",
        description:
          "1-Butterfly Garden, 2-Forb Prairie, 3-Woods-Prairie interface, 4-Mexic Prairie, 5-Old Field, dry, 6-Old Field, Moist, 7-Young Woods, moist, 8-Pole Size Woods, 10-Old Woods, moist, 11-Old Woods, moist, 12-Young Woods, dry",
        s1995: 4,
        s1996: 4,
        s1997: 4,
        s1998: 3,
        s1999: 3,
        s2000: 5,
        s2001: 5,
        s2002: 5,
        s2003: 5,
        s2004: 5,
        createdAt: new Date("3/13/2000 11:30:13 AM GMT-5").toISOString(),
      },
      {
        id: BigInt(19),
        siteName: "Farbach-Werner",
        countyId: countyLookup.Hamilton,
        stateId: stateLookup.Ohio,
        township: "Colerain",
        locationZip: null,
        siteAddress: null,
        siteAddress2: null,
        siteCity: null,
        siteState: null,
        siteZip: null,
        person: "Penny Borgman",
        personAddress: null,
        personAddress2: null,
        personCity: null,
        personState: null,
        personZip: null,
        personPhone: "513 385-4811",
        personEmail: null,
        latitudeStart: null,
        longitudeStart: null,
        latitudeEnd: null,
        longitudeEnd: null,
        altPerson: null,
        altPersonAddress: null,
        altPersonAddress2: null,
        altPersonCity: null,
        altPersonState: null,
        altPersonZip: null,
        altPersonPhone: null,
        altPersonEmail: null,
        otherParticipants: null,
        description: null,
        s1995: 4,
        s1996: 4,
        s1997: 4,
        s1998: 1,
        s1999: 1,
        s2000: 5,
        s2001: 5,
        s2002: 5,
        s2003: 5,
        s2004: 5,
        createdAt: new Date("3/21/2000 10:43:23 AM GMT-5").toISOString(),
      },
      {
        id: BigInt(20),
        siteName: "Coshocton",
        countyId: countyLookup.Coshocton,
        stateId: stateLookup.Ohio,
        township: null,
        locationZip: null,
        siteAddress: null,
        siteAddress2: null,
        siteCity: null,
        siteState: null,
        siteZip: null,
        person: "Jocele Meyer",
        personAddress: "24516 TR 167",
        personAddress2: null,
        personCity: "Fresno",
        personState: "OH",
        personZip: "43834",
        personPhone: null,
        personEmail: "jocelem@clover.net",
        latitudeStart: null,
        longitudeStart: null,
        latitudeEnd: null,
        longitudeEnd: null,
        altPerson: null,
        altPersonAddress: null,
        altPersonAddress2: null,
        altPersonCity: null,
        altPersonState: null,
        altPersonZip: null,
        altPersonPhone: null,
        altPersonEmail: null,
        otherParticipants: null,
        description: null,
        s1995: 4,
        s1996: 4,
        s1997: 4,
        s1998: 4,
        s1999: 5,
        s2000: 5,
        s2001: 5,
        s2002: 5,
        s2003: 5,
        s2004: 5,
        createdAt: new Date("12/15/1999 2:19:36 PM GMT-5").toISOString(),
      },
      {
        id: BigInt(21),
        siteName: "Heston's Wood Lot",
        countyId: countyLookup.Allen,
        stateId: stateLookup.Ohio,
        township: "Bath",
        locationZip: "45801",
        siteAddress: null,
        siteAddress2: null,
        siteCity: null,
        siteState: null,
        siteZip: null,
        person: "B. J. Cole",
        personAddress: "1522 N. Adams St.",
        personAddress2: null,
        personCity: "Lima",
        personState: "OH",
        personZip: "45801",
        personPhone: "419 224-6421",
        personEmail: null,
        latitudeStart: "N40 41'",
        longitudeStart: "W84 04'",
        latitudeEnd: "N40 41'",
        longitudeEnd: "W84 04'",
        altPerson: "Rita Thelan",
        altPersonAddress: "2632 Ada Rd",
        altPersonAddress2: null,
        altPersonCity: "Lima",
        altPersonState: "IO",
        altPersonZip: null,
        altPersonPhone: "419 221-1232",
        altPersonEmail: null,
        otherParticipants: null,
        description:
          "Forest clearing. To the north of transect is an area with mature woods of oak, hickory, & maple. To the south is area of succession. East of transect is old growth oak-hickory. West is area of brambles. Outside of the area on all sides are cleared & mowed grass backyards.",
        s1995: 4,
        s1996: 4,
        s1997: 4,
        s1998: 4,
        s1999: 3,
        s2000: 5,
        s2001: 5,
        s2002: 5,
        s2003: 5,
        s2004: 5,
        createdAt: new Date("3/20/2000 2:14:52 PM GMT-5").toISOString(),
      },
      {
        id: BigInt(22),
        siteName: "Osborne Park Area",
        countyId: countyLookup.Erie,
        stateId: stateLookup.Ohio,
        township: "Huron",
        locationZip: "44839",
        siteAddress: null,
        siteAddress2: null,
        siteCity: null,
        siteState: null,
        siteZip: null,
        person: "Lois TerVeen",
        personAddress: "3910 E. Perkins Ave",
        personAddress2: null,
        personCity: "Huron",
        personState: "OH",
        personZip: "44839-1059",
        personPhone: "419 625-7783",
        personEmail: "EMetroPark@aol.com",
        latitudeStart: "N41 25' 05\"",
        longitudeStart: "W82 38' 15\"",
        latitudeEnd: null,
        longitudeEnd: null,
        altPerson: "Brad Phillips",
        altPersonAddress: "28 E. Main Street",
        altPersonAddress2: null,
        altPersonCity: "Berlin Heights",
        altPersonState: "IO",
        altPersonZip: "44814",
        altPersonPhone: "419 588-2497",
        altPersonEmail: "bradleyd@accnorwalk.com",
        otherParticipants: null,
        description:
          "Large recreational MetroPark with two small woods & large meadow/field area.  Flower beds, woods, lawn, maple grove, fields, brushy ridge, conifers, pond/woods, field/ditch",
        s1995: 4,
        s1996: 4,
        s1997: 4,
        s1998: 4,
        s1999: 3,
        s2000: 5,
        s2001: 5,
        s2002: 5,
        s2003: 5,
        s2004: 5,
        createdAt: new Date("3/20/2000 2:18:03 PM GMT-5").toISOString(),
      },
      {
        id: BigInt(23),
        siteName: "Castalia Quarry Reserve",
        countyId: countyLookup.Erie,
        stateId: stateLookup.Ohio,
        township: "Margaretta",
        locationZip: "44839",
        siteAddress: null,
        siteAddress2: null,
        siteCity: null,
        siteState: null,
        siteZip: null,
        person: "Lois TerVeen",
        personAddress: "3910 E. Perkins Ave",
        personAddress2: null,
        personCity: "Huron",
        personState: "OH",
        personZip: "44839-1059",
        personPhone: "419 625-7783",
        personEmail: "EMetroPark@aol.com",
        latitudeStart: "N 41 23' 25\"",
        longitudeStart: "W 82 49' 55\"",
        latitudeEnd: null,
        longitudeEnd: null,
        altPerson: "Brad Phillips",
        altPersonAddress: "28 E. Main Street",
        altPersonAddress2: "P. O. Box 46",
        altPersonCity: "Berlin Heights",
        altPersonState: "IO",
        altPersonZip: "44814",
        altPersonPhone: "419 588-2497",
        altPersonEmail: "bradleyd@accnorwalk.com",
        otherParticipants: null,
        description:
          "Abandoned limestone quarry turned into a MetroPark.  Heavily forested around the edges; quite dry with two spring fed ponds.  Field, woods, brushy woods, quarry shelf, woods' edge, pond, prairie remnant.",
        s1995: 4,
        s1996: 4,
        s1997: 4,
        s1998: 4,
        s1999: 3,
        s2000: 5,
        s2001: 5,
        s2002: 5,
        s2003: 5,
        s2004: 5,
        createdAt: new Date("3/27/2000 1:07:24 PM GMT-5").toISOString(),
      },
      {
        id: BigInt(24),
        siteName: "James McBride Arboretum",
        countyId: countyLookup.Erie,
        stateId: stateLookup.Ohio,
        township: null,
        locationZip: "44839",
        siteAddress: null,
        siteAddress2: null,
        siteCity: null,
        siteState: null,
        siteZip: null,
        person: "Lois TerVeen",
        personAddress: "3910 E. Perkins Ave",
        personAddress2: null,
        personCity: "Huron",
        personState: "OH",
        personZip: "44839-1059",
        personPhone: "419 625-7783",
        personEmail: "EMetroPark@aol.com",
        latitudeStart: "N41 24',W 82 35' 50'",
        longitudeStart: "N41 24'W 82 35' 50'",
        latitudeEnd: null,
        longitudeEnd: null,
        altPerson: "Diane Hohler-Johnson",
        altPersonAddress: "9502 Church Road",
        altPersonAddress2: null,
        altPersonCity: "Huron",
        altPersonState: "IO",
        altPersonZip: "44839",
        altPersonPhone: "419 588-2779",
        altPersonEmail: null,
        otherParticipants: "Brad Phillips",
        description:
          "Young developing arboretum with small woods, located behind BGSU Firelands Ca,pus.  Meadow, woods, brushy ditch, meadow, bluebird trail, spruces, prairie, arboretum, grass",
        s1995: 4,
        s1996: 4,
        s1997: 4,
        s1998: 4,
        s1999: 3,
        s2000: 5,
        s2001: 5,
        s2002: 5,
        s2003: 5,
        s2004: 5,
        createdAt: new Date("3/27/2000 2:22:11 PM GMT-5").toISOString(),
      },
      {
        id: BigInt(25),
        siteName: "Krebs Farm",
        countyId: countyLookup.Erie,
        stateId: stateLookup.Ohio,
        township: null,
        locationZip: "44839",
        siteAddress: null,
        siteAddress2: null,
        siteCity: null,
        siteState: null,
        siteZip: null,
        person: "Lois TerVeen",
        personAddress: "3910 E. Perkins Ave",
        personAddress2: "305 Douglas Dr., Bellview, OH 44839",
        personCity: "Huron",
        personState: "OH",
        personZip: "44839-1059",
        personPhone: "419 625-4217",
        personEmail: "emetropark@aol.com",
        latitudeStart: "N 41 25' 00\"",
        longitudeStart: "W82 36' 45\"",
        latitudeEnd: null,
        longitudeEnd: null,
        altPerson: "Brad Phillips",
        altPersonAddress: "28 E. Main Street",
        altPersonAddress2: "P. O. Box 46",
        altPersonCity: "Berlin Heights",
        altPersonState: "OH",
        altPersonZip: "44814",
        altPersonPhone: "419 588-2497",
        altPersonEmail: "bradleyd@accnorwalk.com",
        otherParticipants: "Pat Krebs",
        description:
          "Wooded lowland, evergreen hedge, meadow, thickety edge, wet meadow, old field, pear hedgerow, wildflower patch, clover meadow, hackberry hedgerow",
        s1995: 4,
        s1996: 4,
        s1997: 4,
        s1998: 4,
        s1999: 3,
        s2000: 5,
        s2001: 5,
        s2002: 5,
        s2003: 5,
        s2004: 5,
        createdAt: new Date("3/27/2000 1:53:49 PM GMT-5").toISOString(),
      },
      {
        id: BigInt(26),
        siteName: "Oak Openings",
        countyId: countyLookup.Lucas,
        stateId: stateLookup.Ohio,
        township: "Swanton",
        locationZip: null,
        siteAddress: null,
        siteAddress2: null,
        siteCity: null,
        siteState: null,
        siteZip: null,
        person: "Denise Gehring",
        personAddress: "5100 W. Central Avenue",
        personAddress2: "X102",
        personCity: "Toledo",
        personState: "OH",
        personZip: "43615",
        personPhone: "419 535-3058",
        personEmail: "naturalist@glass.city.net",
        latitudeStart: "N 83 50' 41\".7",
        longitudeStart: "W 41 32' 07.2\"",
        latitudeEnd: "Same",
        longitudeEnd: "Same",
        altPerson: "Karen Menard",
        altPersonAddress: "5100 W. Central Avenue",
        altPersonAddress2: "X105",
        altPersonCity: "Toledo",
        altPersonState: "OH",
        altPersonZip: "43615",
        altPersonPhone: "419 535-3058",
        altPersonEmail: "naturalist@glass.city.net",
        otherParticipants:
          "Linda Munger, Monique Mendietta, Lesley Royce, Erin Pearson, Bob Hay, Steve Smith, Heather Norris",
        description:
          "Loop slightly under 1 mile. Through oak woodland, degraded wet prairie, tall grass prairie, dune area, wet meadow, oak savanna.",
        s1995: 4,
        s1996: 4,
        s1997: 4,
        s1998: 4,
        s1999: 3,
        s2000: 5,
        s2001: 5,
        s2002: 5,
        s2003: 5,
        s2004: 5,
        createdAt: new Date("6/27/2000 10:17:32 AM GMT-5").toISOString(),
      },
      {
        id: BigInt(27),
        siteName: "Top Of The World",
        countyId: countyLookup.Summit,
        stateId: stateLookup.Ohio,
        township: null,
        locationZip: "44313",
        siteAddress: null,
        siteAddress2: null,
        siteCity: null,
        siteState: null,
        siteZip: null,
        person: "Pat Rydquist",
        personAddress: "1828 Smith Road",
        personAddress2: "Hm:2274 Victoria Pky, Hudson, Ohio 44236",
        personCity: "Akron",
        personState: "OH",
        personZip: "44313",
        personPhone: "330 865-8065",
        personEmail: "rydquist@oh.verio.com",
        latitudeStart: "N41 10.031",
        longitudeStart: "W81 32.0944",
        latitudeEnd: "N41 10.127",
        longitudeEnd: "W81 32.991",
        altPerson: "Alice Phillips",
        altPersonAddress: "1383 Delia Avenue",
        altPersonAddress2: null,
        altPersonCity: "Akron",
        altPersonState: "IO",
        altPersonZip: "44320",
        altPersonPhone: "330 867-5482",
        altPersonEmail: null,
        otherParticipants: "M. Siebert",
        description:
          "Hampton Hills Metro Park: Old barn, pond, old orchard, fields, forest margin, food plots planted by Metro Parks for wildlife.",
        s1995: 4,
        s1996: 4,
        s1997: 4,
        s1998: 4,
        s1999: 3,
        s2000: 5,
        s2001: 5,
        s2002: 5,
        s2003: 5,
        s2004: 5,
        createdAt: new Date("3/28/2000 1:47:15 PM GMT-5").toISOString(),
      },
      {
        id: BigInt(28),
        siteName: "Cincinnati Nature Center",
        countyId: countyLookup.Clermont,
        stateId: stateLookup.Ohio,
        township: "Union",
        locationZip: "45150",
        siteAddress: null,
        siteAddress2: null,
        siteCity: null,
        siteState: null,
        siteZip: null,
        person: "Yvonne Mohlman",
        personAddress: "P. O. Box 27028",
        personAddress2: null,
        personCity: "Cincinnati",
        personState: "OH",
        personZip: "45227",
        personPhone: "513 677-0571",
        personEmail: null,
        latitudeStart: "N39 07 34",
        longitudeStart: "W84 14 43.3",
        latitudeEnd: "N84 14 43.3",
        longitudeEnd: "W84 14 27.7",
        altPerson: "Harriet Clark",
        altPersonAddress: "4949 Tealton Road",
        altPersonAddress2: null,
        altPersonCity: "Milford",
        altPersonState: "OH",
        altPersonZip: "45150",
        altPersonPhone: "513 831-1711",
        altPersonEmail: null,
        otherParticipants: "Harriet Clark",
        description:
          "LongituteEnd appears in ERROR.  1 1/2 mile trail beginning at Butterfly Garden just outside main (Rowe) building, following mowed path through fields, wooded areas, past 2 ponds, ending at marker#27 on Lookout Trail.",
        s1995: 4,
        s1996: 4,
        s1997: 4,
        s1998: 4,
        s1999: 3,
        s2000: 5,
        s2001: 5,
        s2002: 5,
        s2003: 5,
        s2004: 5,
        createdAt: new Date("4/18/2000 1:25:28 PM GMT-5").toISOString(),
      },
      {
        id: BigInt(29),
        siteName: "NCR-Bluebird Field",
        countyId: countyLookup.Cuyahoga,
        stateId: stateLookup.Ohio,
        township: null,
        locationZip: null,
        siteAddress: null,
        siteAddress2: null,
        siteCity: null,
        siteState: null,
        siteZip: null,
        person: "Deb Marcinski",
        personAddress: "3037 SOM Center Road",
        personAddress2: null,
        personCity: "Willoughby Hills",
        personState: "OH",
        personZip: "44094",
        personPhone: "440 473-3370",
        personEmail: null,
        latitudeStart: "N41 33.988",
        longitudeStart: "W 81 24.025",
        latitudeEnd: null,
        longitudeEnd: null,
        altPerson: null,
        altPersonAddress: null,
        altPersonAddress2: null,
        altPersonCity: null,
        altPersonState: null,
        altPersonZip: null,
        altPersonPhone: null,
        altPersonEmail: null,
        otherParticipants: "Kevin Metcalf, Tim Krynak",
        description: null,
        s1995: 4,
        s1996: 3,
        s1997: 3,
        s1998: 4,
        s1999: 4,
        s2000: 5,
        s2001: 5,
        s2002: 5,
        s2003: 5,
        s2004: 5,
        createdAt: new Date("3/20/2000 2:16:27 PM GMT-5").toISOString(),
      },
      {
        id: BigInt(30),
        siteName: "NCR-Rogers Road",
        countyId: countyLookup.Cuyahoga,
        stateId: stateLookup.Ohio,
        township: null,
        locationZip: null,
        siteAddress: null,
        siteAddress2: null,
        siteCity: null,
        siteState: null,
        siteZip: null,
        person: "Deb Marcinski",
        personAddress: "3037 SOM Center Road",
        personAddress2: null,
        personCity: "Willoughby Hills",
        personState: "OH",
        personZip: "44094",
        personPhone: "440 473-3370",
        personEmail: null,
        latitudeStart: "N41 34.216",
        longitudeStart: "W81 24.835",
        latitudeEnd: null,
        longitudeEnd: null,
        altPerson: null,
        altPersonAddress: null,
        altPersonAddress2: null,
        altPersonCity: null,
        altPersonState: null,
        altPersonZip: null,
        altPersonPhone: null,
        altPersonEmail: null,
        otherParticipants: null,
        description: null,
        s1995: 4,
        s1996: 3,
        s1997: 3,
        s1998: 4,
        s1999: 4,
        s2000: 5,
        s2001: 5,
        s2002: 5,
        s2003: 5,
        s2004: 5,
        createdAt: new Date("3/20/2000 2:16:51 PM GMT-5").toISOString(),
      },
      {
        id: BigInt(31),
        siteName: "NCR-Strawberry Field",
        countyId: countyLookup.Cuyahoga,
        stateId: stateLookup.Ohio,
        township: null,
        locationZip: null,
        siteAddress: null,
        siteAddress2: null,
        siteCity: null,
        siteState: null,
        siteZip: null,
        person: "Deb Marcinski",
        personAddress: "3037 SOM Center Road",
        personAddress2: null,
        personCity: "Willoughby Hills",
        personState: "OH",
        personZip: "44094",
        personPhone: "440 473-3370",
        personEmail: null,
        latitudeStart: "N41 34.68",
        longitudeStart: "W81 25.974",
        latitudeEnd: null,
        longitudeEnd: null,
        altPerson: null,
        altPersonAddress: null,
        altPersonAddress2: null,
        altPersonCity: null,
        altPersonState: null,
        altPersonZip: null,
        altPersonPhone: null,
        altPersonEmail: null,
        otherParticipants: null,
        description: null,
        s1995: 4,
        s1996: 3,
        s1997: 3,
        s1998: 4,
        s1999: 4,
        s2000: 5,
        s2001: 5,
        s2002: 5,
        s2003: 5,
        s2004: 5,
        createdAt: new Date("3/20/2000 2:17:10 PM GMT-5").toISOString(),
      },
      {
        id: BigInt(32),
        siteName: "NCR-Maintenance Meadow",
        countyId: countyLookup.Cuyahoga,
        stateId: stateLookup.Ohio,
        township: null,
        locationZip: null,
        siteAddress: null,
        siteAddress2: null,
        siteCity: null,
        siteState: null,
        siteZip: null,
        person: "Deb Marcinski",
        personAddress: "3037 SOM Center Road",
        personAddress2: null,
        personCity: "Willoughby Hills",
        personState: "OH",
        personZip: "44094",
        personPhone: "440 473-3370",
        personEmail: null,
        latitudeStart: null,
        longitudeStart: null,
        latitudeEnd: null,
        longitudeEnd: null,
        altPerson: null,
        altPersonAddress: null,
        altPersonAddress2: null,
        altPersonCity: null,
        altPersonState: null,
        altPersonZip: null,
        altPersonPhone: null,
        altPersonEmail: null,
        otherParticipants: "Kevin Metcalf, Karpinski, Cherry",
        description: null,
        s1995: 4,
        s1996: 3,
        s1997: 3,
        s1998: 4,
        s1999: 4,
        s2000: 5,
        s2001: 5,
        s2002: 5,
        s2003: 5,
        s2004: 5,
        createdAt: new Date("12/28/1999 1:45:20 PM GMT-5").toISOString(),
      },
      {
        id: BigInt(34),
        siteName: "Beavercreek Wildlife Area",
        countyId: countyLookup.Greene,
        stateId: stateLookup.Ohio,
        township: "Beavercreek",
        locationZip: "45385",
        siteAddress: null,
        siteAddress2: null,
        siteCity: null,
        siteState: null,
        siteZip: null,
        person: "Lynn Holtzman",
        personAddress: "1076 Old Springfield Pike",
        personAddress2: "Ohio Div, Of Wildlife - Distrist 5",
        personCity: "Xenia",
        personState: "IO",
        personZip: "45385-1238",
        personPhone: "437 372-9261",
        personEmail: "Lynn.Holtzman.@odnr.state.oh.u",
        latitudeStart: "N39 44' 18.65\"",
        longitudeStart: "W84 0' 45.26\"",
        latitudeEnd: "N39 44' 15.17",
        longitudeEnd: "W84 0' 39.60\"",
        altPerson: null,
        altPersonAddress: null,
        altPersonAddress2: null,
        altPersonCity: null,
        altPersonState: null,
        altPersonZip: null,
        altPersonPhone: null,
        altPersonEmail: null,
        otherParticipants: "Shane R. Hemon",
        description:
          "Natural wetland complex, containing sedge meadow (fen), scrub shrubs, wet woods, hardwood wetland communities.",
        s1995: 4,
        s1996: 4,
        s1997: 4,
        s1998: 4,
        s1999: 3,
        s2000: 5,
        s2001: 5,
        s2002: 5,
        s2003: 5,
        s2004: 5,
        createdAt: new Date("4/10/2000 1:22:58 PM GMT-5").toISOString(),
      },
      {
        id: BigInt(35),
        siteName: "Blacklick Park",
        countyId: countyLookup.Franklin,
        stateId: stateLookup.Ohio,
        township: null,
        locationZip: null,
        siteAddress: null,
        siteAddress2: null,
        siteCity: null,
        siteState: null,
        siteZip: null,
        person: "John & Cindy Cooper",
        personAddress: "11781 Julie Drive",
        personAddress2: null,
        personCity: "Baltimore",
        personState: "IO",
        personZip: "43105",
        personPhone: "740 862-6373",
        personEmail: "john_cooper@dscc.dla.mil",
        latitudeStart: null,
        longitudeStart: null,
        latitudeEnd: null,
        longitudeEnd: null,
        altPerson: null,
        altPersonAddress: null,
        altPersonAddress2: null,
        altPersonCity: null,
        altPersonState: null,
        altPersonZip: null,
        altPersonPhone: null,
        altPersonEmail: null,
        otherParticipants: null,
        description: null,
        s1995: 4,
        s1996: 4,
        s1997: 4,
        s1998: 4,
        s1999: 3,
        s2000: 5,
        s2001: 5,
        s2002: 5,
        s2003: 5,
        s2004: 5,
        createdAt: new Date("3/2/2000 10:00:33 AM GMT-5").toISOString(),
      },
      {
        id: BigInt(37),
        siteName: "Jude's Butterfly Trail",
        countyId: countyLookup.Montgomery,
        stateId: stateLookup.Ohio,
        township: "Jackson",
        locationZip: "45325",
        siteAddress: null,
        siteAddress2: null,
        siteCity: null,
        siteState: null,
        siteZip: null,
        person: "Judy Evans",
        personAddress: "121 Dayton-Farmersville Road",
        personAddress2: null,
        personCity: "Farmersville",
        personState: "IO",
        personZip: "45325",
        personPhone: "937 696-2063",
        personEmail: null,
        latitudeStart: null,
        longitudeStart: null,
        latitudeEnd: null,
        longitudeEnd: null,
        altPerson: null,
        altPersonAddress: null,
        altPersonAddress2: null,
        altPersonCity: null,
        altPersonState: null,
        altPersonZip: null,
        altPersonPhone: null,
        altPersonEmail: null,
        otherParticipants: null,
        description:
          "Small farm, 1 mile east of Farmersville. All fence rows overgrown & undisturbed for at least 15 years. Flat to rolling ground. Crop fields, small pond, mowed paths in rolling tree studded uncultivated field.",
        s1995: 4,
        s1996: 4,
        s1997: 4,
        s1998: 4,
        s1999: 3,
        s2000: 5,
        s2001: 5,
        s2002: 5,
        s2003: 5,
        s2004: 5,
        createdAt: new Date("1/13/2000 11:21:20 AM GMT-5").toISOString(),
      },
      {
        id: BigInt(39),
        siteName: "OR79-147JER",
        countyId: countyLookup.Hocking,
        stateId: stateLookup.Ohio,
        township: "Perry",
        locationZip: "43135",
        siteAddress: null,
        siteAddress2: null,
        siteCity: null,
        siteState: null,
        siteZip: null,
        person: "Joe Riddlebarger",
        personAddress: "21080 Thompson Rd",
        personAddress2: null,
        personCity: "Laurelville",
        personState: "OH",
        personZip: "43135",
        personPhone: "740-332-9017",
        personEmail: "alyfab@ccia.com",
        latitudeStart: "N29 0' 0\"",
        longitudeStart: "W82 38' 30\"",
        latitudeEnd: null,
        longitudeEnd: null,
        altPerson: "Lynn Lanning",
        altPersonAddress: "610 Greenspring Dr",
        altPersonAddress2: null,
        altPersonCity: "Gibsonia",
        altPersonState: "PA",
        altPersonZip: "15044",
        altPersonPhone: "724-443-5718",
        altPersonEmail: null,
        otherParticipants: "Halle Riddlebarger",
        description:
          "North facing, wooded hillside sloping from an elevation of approx. 1050 ft down to 900 ft ending at a small flood plain and stream.  Mostly wooded with few mature trees.  Mixed hardwoods and evergreens.  It is 2 miles west of Rockhouse State Park on Thompson Ridge which faces the line of glacial advance into Hocking Co.  The road ends at SR 56 in Laurelville, OH.  Small house with deck and view.",
        s1995: 4,
        s1996: 4,
        s1997: 4,
        s1998: 4,
        s1999: 3,
        s2000: 5,
        s2001: 5,
        s2002: 5,
        s2003: 5,
        s2004: 5,
        createdAt: new Date("3/20/2000 2:17:47 PM GMT-5").toISOString(),
      },
      {
        id: BigInt(40),
        siteName: "Greenacres Foundation",
        countyId: countyLookup.Hamilton,
        stateId: stateLookup.Ohio,
        township: "Village Of Indian Hill",
        locationZip: "45242",
        siteAddress: null,
        siteAddress2: null,
        siteCity: null,
        siteState: null,
        siteZip: null,
        person: "Heather Summerville",
        personAddress: "8255 Spooky Hollow Rd",
        personAddress2: "Greenacres Foundation",
        personCity: "Cincinnati",
        personState: "OH",
        personZip: "45242",
        personPhone: "513-891-4227",
        personEmail: "hsummerville@green-acres.org",
        latitudeStart: "N39 16' 32',W 84 25' 18'",
        longitudeStart: "N39 16'W 84 25' 18'",
        latitudeEnd: "N39 16' 32\"",
        longitudeEnd: "W84 25' 18\"",
        altPerson: "Keith Summerville",
        altPersonAddress: null,
        altPersonAddress2: null,
        altPersonCity: null,
        altPersonState: null,
        altPersonZip: null,
        altPersonPhone: "513-524-8996",
        altPersonEmail: null,
        otherParticipants: "Phillippe Polman",
        description:
          "Trail begins at Greenacres Field Office, located at corner of spooky Hollow and Loveland-Madeira Rds.  Follow bridal trail west, along Sycamore Cr; head south at end of trail into field (mowed path); folow to bee hives; acend trail into woods; decend trail to gardens; end at butterfly garden.",
        s1995: 4,
        s1996: 4,
        s1997: 4,
        s1998: 4,
        s1999: 3,
        s2000: 5,
        s2001: 5,
        s2002: 5,
        s2003: 5,
        s2004: 5,
        createdAt: new Date("3/27/2000 2:10:04 PM GMT-5").toISOString(),
      },
      {
        id: BigInt(42),
        siteName: "Alrutz Loop",
        countyId: countyLookup.Licking,
        stateId: stateLookup.Ohio,
        township: "Granville",
        locationZip: "43023",
        siteAddress: null,
        siteAddress2: null,
        siteCity: null,
        siteState: null,
        siteZip: null,
        person: "Tom D. Schultz",
        personAddress: "Dept. Of Biology",
        personAddress2: "Denison University",
        personCity: "Granville",
        personState: "IO",
        personZip: "43023",
        personPhone: "740 587-6218",
        personEmail: "schultz@denison.edu",
        latitudeStart: "N40 05.006",
        longitudeStart: "W082 31.188",
        latitudeEnd: "N 40 05.100",
        longitudeEnd: "W",
        altPerson: null,
        altPersonAddress: null,
        altPersonAddress2: null,
        altPersonCity: null,
        altPersonState: null,
        altPersonZip: null,
        altPersonPhone: null,
        altPersonEmail: null,
        otherParticipants: "Ann Voight, H. Menninger, Kate Krulia",
        description:
          "Start at field station; early succession field bordered by hedgerow; Section between pine plantation and forest; young woods with old-field orchard, includes marsh; field; older woods with dry hillside; successional field wirh wetland & hedgerow; field bordering woods; fields with some woods; old field habitat with secondary growth & orchard; early field with disturbed habitat.",
        s1995: 4,
        s1996: 4,
        s1997: 4,
        s1998: 3,
        s1999: 3,
        s2000: 5,
        s2001: 5,
        s2002: 5,
        s2003: 5,
        s2004: 5,
        createdAt: new Date("8/22/2000 1:27:06 PM GMT-5").toISOString(),
      },
      {
        id: BigInt(43),
        siteName: "Clear Creek Metro Park",
        countyId: countyLookup.Hocking,
        stateId: stateLookup.Ohio,
        township: "Good Hope",
        locationZip: null,
        siteAddress: null,
        siteAddress2: null,
        siteCity: null,
        siteState: null,
        siteZip: null,
        person: "John Watts",
        personAddress: "1069 West Main Street",
        personAddress2: null,
        personCity: "Westerville",
        personState: "OH",
        personZip: "43081",
        personPhone: "614 891-0700",
        personEmail: null,
        latitudeStart: null,
        longitudeStart: null,
        latitudeEnd: null,
        longitudeEnd: null,
        altPerson: null,
        altPersonAddress: null,
        altPersonAddress2: null,
        altPersonCity: null,
        altPersonState: null,
        altPersonZip: null,
        altPersonPhone: null,
        altPersonEmail: null,
        otherParticipants: "R. Bates, J. Davidson",
        description:
          "Old field; Mowed trail and old field; Mowed trail and Ood field with winged sumac; Old field with mowed trail; Old field Old field along wood edge and mowed path, passes through successional woods; Old field.",
        s1995: 4,
        s1996: 4,
        s1997: 4,
        s1998: 4,
        s1999: 3,
        s2000: 5,
        s2001: 5,
        s2002: 5,
        s2003: 5,
        s2004: 5,
        createdAt: new Date("5/1/2000 11:45:56 AM GMT-5").toISOString(),
      },
      {
        id: BigInt(45),
        siteName: "Thoreau Wildlife Sanctuary",
        countyId: countyLookup.Defiance,
        stateId: stateLookup.Ohio,
        township: "Noble",
        locationZip: null,
        siteAddress: null,
        siteAddress2: null,
        siteCity: null,
        siteState: null,
        siteZip: null,
        person: "Dr. Karen E. McCracken",
        personAddress: "Dept. Of Natural Sciences",
        personAddress2: "701 N. Clinton",
        personCity: "Defiance",
        personState: "OH",
        personZip: "43512",
        personPhone: "419 784-0426",
        personEmail: "kmccracken@defiance.edu",
        latitudeStart: null,
        longitudeStart: null,
        latitudeEnd: null,
        longitudeEnd: null,
        altPerson: null,
        altPersonAddress: null,
        altPersonAddress2: null,
        altPersonCity: null,
        altPersonState: null,
        altPersonZip: null,
        altPersonPhone: null,
        altPersonEmail: null,
        otherParticipants: null,
        description: null,
        s1995: 4,
        s1996: 4,
        s1997: 4,
        s1998: 4,
        s1999: 3,
        s2000: 5,
        s2001: 5,
        s2002: 5,
        s2003: 5,
        s2004: 5,
        createdAt: new Date("3/21/2000 12:03:54 PM GMT-5").toISOString(),
      },
      {
        id: BigInt(46),
        siteName: "Kelleys Island - Coleman Tract",
        countyId: countyLookup.Erie,
        stateId: stateLookup.Ohio,
        township: "Kelleys Island",
        locationZip: "43438",
        siteAddress: null,
        siteAddress2: null,
        siteCity: null,
        siteState: null,
        siteZip: null,
        person: "Barbara K. Coleman",
        personAddress: "14916 Arden Avenue",
        personAddress2: null,
        personCity: "Lakewood",
        personState: "IO",
        personZip: "44107",
        personPhone: "216 226 0391",
        personEmail: "CMNHdocent@aol.com",
        latitudeStart: null,
        longitudeStart: null,
        latitudeEnd: null,
        longitudeEnd: null,
        altPerson: "William G. Coleman",
        altPersonAddress: "Same",
        altPersonAddress2: null,
        altPersonCity: null,
        altPersonState: null,
        altPersonZip: null,
        altPersonPhone: null,
        altPersonEmail: null,
        otherParticipants: null,
        description:
          "East and parallel to K.I.-Bookerman site. Brush-hogged summer of 1999. Cleveland Museum of Natural History property. Woods - Sec. 1, 7, & 8. Edge of field - Sec, 2,3,4, & 6. Path through over-grown old vineyard. Limestone underlying rock.",
        s1995: 4,
        s1996: 4,
        s1997: 4,
        s1998: 4,
        s1999: 4,
        s2000: 1,
        s2001: 5,
        s2002: 5,
        s2003: 5,
        s2004: 5,
        createdAt: new Date("6/26/2000 9:48:14 AM GMT-5").toISOString(),
      },
      {
        id: BigInt(47),
        siteName: "Shaker Trace Wetlands",
        countyId: countyLookup.Hamilton,
        stateId: stateLookup.Ohio,
        township: null,
        locationZip: null,
        siteAddress: null,
        siteAddress2: null,
        siteCity: null,
        siteState: null,
        siteZip: null,
        person: "Steve Pelikan",
        personAddress: "8 Tanglewood Lane",
        personAddress2: null,
        personCity: "Cincinnati",
        personState: "OH",
        personZip: "45224",
        personPhone: "513 556-4084",
        personEmail: "pelikan@math.uc.edu",
        latitudeStart: null,
        longitudeStart: null,
        latitudeEnd: null,
        longitudeEnd: null,
        altPerson: null,
        altPersonAddress: null,
        altPersonAddress2: null,
        altPersonCity: null,
        altPersonState: null,
        altPersonZip: null,
        altPersonPhone: null,
        altPersonEmail: null,
        otherParticipants: "C. Saunders, N. Saunders",
        description: null,
        s1995: 4,
        s1996: 5,
        s1997: 5,
        s1998: 5,
        s1999: 3,
        s2000: 5,
        s2001: 5,
        s2002: 5,
        s2003: 5,
        s2004: 5,
        createdAt: new Date("9/26/2000 2:45:58 PM GMT-5").toISOString(),
      },
      {
        id: BigInt(48),
        siteName: "McLean Teddy Bear Park",
        countyId: countyLookup.Allen,
        stateId: stateLookup.Ohio,
        township: "Bath",
        locationZip: "45801",
        siteAddress: "North Dixie Highway",
        siteAddress2: null,
        siteCity: null,
        siteState: null,
        siteZip: null,
        person: "Rita Thelen",
        personAddress: "2355 Ada Rd",
        personAddress2: null,
        personCity: "Lima",
        personState: "OH",
        personZip: "45801",
        personPhone: "419 221-1232",
        personEmail: "jampd@wcoil.com",
        latitudeStart: "N 40 45",
        longitudeStart: "W 84 04",
        latitudeEnd: "N 40 45",
        longitudeEnd: "W 84 04",
        altPerson: "Mark Mohr",
        altPersonAddress: "2355 Ada Rd",
        altPersonAddress2: null,
        altPersonCity: "Lima",
        altPersonState: "OH",
        altPersonZip: "45801",
        altPersonPhone: "419 221-1232",
        altPersonEmail: "jampd@wcoil.com",
        otherParticipants:
          "Frank Pauff, Bob Obermeyer, BJ Cole, Patty & Marie Iszorry, Debbie Hanlin",
        description:
          "Located 1/4 mile NE of St Rt 81 on North Dixie Highway.  Route begins near the trailhead between the east and west prairie.  Park in the main lot and walk north to the top of hill.  Route is divided into five sections traveling through prairie, meadow, mixed early succession and wooded areas.  It is approximately 1,426 feet and 4 inches in length..",
        s1995: 4,
        s1996: 4,
        s1997: 4,
        s1998: 4,
        s1999: 4,
        s2000: 1,
        s2001: 5,
        s2002: 5,
        s2003: 5,
        s2004: 5,
        createdAt: new Date("10/5/2000 9:51:55 AM GMT-5").toISOString(),
      },
    ],
  });

  await db.$executeRaw`
insert into section
(description, labelLong, labelShort, sectionIndex, siteId)
select concat('Section ', x.y) description
, concat('Section ', x.y) labelLong
, concat('S', x.y) labelShort
, x.y sectionIndex
, s.id
from site s
join (select 1 y
union select 2 y
union select 3 y
union select 4 y
union select 5 y
union select 6 y
union select 7 y
union select 8 y
union select 9 y
union select 10 y
union select 11 y
union select 12 y
union select 13 y
union select 14 y
union select 15 y) x
`;
}
